### ISSUE TITLE
error: missing top-level 'paths' field

### ISSUE THREAD

**Issue by xiusin** [thechampagne/webview-zig#1]
Currently, it is not possible to compile using `build.zig.zon` and manage this dependency using `zigmod`

```
F:\projects\webview-zig\examples\basic\build.zig.zon:1:2: error: missing top-level 'paths' field
```

**Comment by thechampagne** [comment]
Maybe this is introduced on newer version.
My zig version is `0.12.0-dev.789+e6590fea1`.

**Comment by xiusin** [comment]
Fixed it by adding:

```
.paths = .{""},
```
